id: ID5788066
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T21:24:35+00:00'
last_modified: '2022-06-08T10:51:33.973597+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD90008
  title: ལི་ཐང་རྫོང་གི་ལོ་རྒྱུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    98BB:
      image_group_id: I1PD90061
      title: ''
      total_pages: 602
      order: 1
      base_file: 98BB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
