id: P009413
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD90008
  title: ལི་ཐང་རྫོང་གི་ལོ་རྒྱུས།
  author: ''
  volumes:
    edeca77f182b48f2b6f117ae6d473a87:
      image_group_id: I1PD90061
      title: ''
      volume_number: 1
      total_pages: 602
      base_file: v001.txt
